name: #京豆变动通知 #疯狂的joy #京东排行榜 #领京豆额外奖励 #京东年货节


on:
  push:
  gollum:
  schedule:
  - cron: "30 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # 使用 node:10
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    # npm install
    - name: "运行  #京豆变动通知 #疯狂的joy #京东排行榜 #领京豆额外奖励 #京东年货节"
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
      run: |
        npm install
        node jd_bean_change
        node jd_crazy_joy
        node jd_rankingList
        node jd_bean_home
        node jd_car
        node jd_nh
